### ISSUE TITLE
Code availability

### ISSUE THREAD

**Issue by HannahKirk** [sashrikap/context-steering#1]
Hi!

When will the code be made available?

I enjoyed reading the preprint: https://arxiv.org/pdf/2405.01768

All the best,

Hannah

**Comment by sashrikap** [comment]
Hi Hannah, thanks for your interest! We're aiming to release by early July.

**Comment by bzhangj13zzz** [comment]
Hi! Is there any update on this? Thanks!

**Comment by sashrikap** [comment]
our planned release date was pushed to august, thanks for your interest!

**Comment by hrk-aisi** [comment]
Hi, is there an update on this?

**Comment by sashrikap** [comment]
Still in progress but I’ll respond to this thread when the code is up

**Comment by hrk-aisi** [comment]
Hi, is there any update on the code?

**Comment by sashrikap** [comment]
Thanks for your patience! Code is up :)
